image: docker
services:
  - docker:dind
stages:
  - deploy
step-deploy-prod:
  stage: deploy
  script:
    - docker build -t app/final_hh_project_admin_web .
    - docker run -d -p 80:80 --rm --name adminweb app/final_hh_project_admin_web
